### ISSUE TITLE
error sfntwoff ...

### ISSUE THREAD

**Issue by CarterWebDev** [zoltan-dulac/css3FontConverter#3]
iam gettin an error sayin sfntwoff is not installed.
what to do :/

**Comment by zoltan-dulac** [comment]
Since EOTFAST is the only application that people had downloading in the past, I have updated the repo to include it by default (Thanks to Richard Fink (http://readableweb.com/) for kindly letting me do this).

SInce the others are readily available, I will close this for now. Please read the readme file in the git repo for information about where to get the other applications.
